### ISSUE TITLE
please VersionChecksum unset

### ISSUE THREAD

**Issue by RichardoC** [ocurity/dracon#3]
## Issue

The [VersionChecksum](https://please.build/config.html#please.versionchecksum) should be pinned, as well as the plz version in the .plzconfig to prevent possible supply chain tampering.

### Expected behaviour
Please should fail to install a tampered version

### Actual behaviour
Please would install a tampered version with mismatching checksum

### Steps to reproduce
N/A

**Comment by northdpole** [comment]
thanks for this, working on it
