### ISSUE TITLE
Re-evaluate please.build feasibility

### ISSUE THREAD

**Issue by northdpole** [ocurity/dracon#43]
## Issue
please.build is relatively familiar to the current project maintainers and as a build system it does make life easier if you use it precisely as intented and with the intended plugins.

however most people do not know about please, the community is minimal hence bugs are hard to search for, moreover as a relatively small build system it is not as user friendly as it should be 

(e.g. if you mixup config by not defining plugins, it tells you that random paths depend on //:all which it cannot build, instead of producing a better error)

We are currently using please v16 since please v17 has a lot of breaking changes.
we should evaluate if it makes sense to upgrade to please 17 and if it doesn't, we should replace it with either bazel of makefiles.

**Comment by ptzianos** [comment]
Fixed as part of https://github.com/ocurity/dracon/pull/53
